# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'



  - task: CopyPublishBuildArtifacts@1
    inputs:
      CopyRoot: 'vjb'
      Contents: 'bkn'
      ArtifactName: 'gikh'
      ArtifactType: 'Container'



- task: CopyFiles@2
  inputs:
    SourceFolder: 'gi'
    Contents: '**'
    TargetFolder: 'oho'


- task: WindowsMachineFileCopy@2
  inputs:
    SourcePath: 'ljl'
    MachineNames: 'lnln'
    AdminUserName: 'knk'
    AdminPassword: 'khho'
    TargetPath: 'nkn'


- task: CopyPublishBuildArtifacts@1
  inputs:
    CopyRoot: 'g'
    Contents: '**'
    ArtifactName: 'jb'
    ArtifactType: 'Container'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
